In [1]:
# connect to snowflake

%reload_ext snowflakes
%snowflakes FUSION_FDR_ETL_USER FsW@1fDrR pitneybowes.us-east-1

In [2]:
%%snowflakes DFW1

SELECT
    PARCELKEY, FACILITYNAME, MACHINEID, CREATIONTIME, LENGTH, WIDTH, HEIGHT, WEIGHT
FROM
    "FDR_DWH_DB_PROD"."PARCELAUTOMATION"."PARCEL"
WHERE
    CREATIONTIME >= '2021-05-01' AND CREATIONTIME < '2021-05-16' AND FACILITYNAME = 'DFW4' AND LENGTH != 0 AND WEIGHT != 0;

,PARCELKEY,FACILITYNAME,MACHINEID,CREATIONTIME,LENGTH,WIDTH,HEIGHT,WEIGHT
0,718936886,DFW4,7,2021-05-11 20:40:27.470,241.0,120.0,151.0,1350.0
1,718921236,DFW4,7,2021-05-11 20:13:13.910,399.0,85.0,348.0,801.0
2,718911692,DFW4,7,2021-05-11 20:00:58.550,300.0,124.0,220.0,2796.0
3,718935848,DFW4,7,2021-05-11 20:39:03.213,314.0,71.0,222.0,703.0
4,718975693,DFW4,7,2021-05-11 21:31:22.053,388.0,144.0,308.0,2782.0
...,...,...,...,...,...,...,...,...
1071470,709790105,DFW4,7,2021-05-01 00:02:20.110,367.0,79.0,309.0,645.0
1071471,709823493,DFW4,8,2021-05-01 00:37:29.203,315.0,82.0,260.0,312.0
1071472,709821610,DFW4,7,2021-05-01 00:36:02.850,210.0,43.0,108.0,110.0
1071473,709861029,DFW4,7,2021-05-01 01:41:21.230,480.0,108.0,432.0,1758.0
1071474,709803266,DFW4,7,2021-05-01 00:18:03.120,277.0,47.0,245.0,190.0

In [3]:
DFW1.to_csv('DFW1.csv')

In [4]:
%%snowflakes DFW2

SELECT
    PARCELKEY, FACILITYNAME, MACHINEID, CREATIONTIME, LENGTH, WIDTH, HEIGHT, WEIGHT
FROM
    "FDR_DWH_DB_PROD"."PARCELAUTOMATION"."PARCEL"
WHERE
    CREATIONTIME >= '2021-05-16' AND CREATIONTIME < '2021-06-01' AND FACILITYNAME = 'DFW4' AND LENGTH != 0 AND WEIGHT != 0;

,PARCELKEY,FACILITYNAME,MACHINEID,CREATIONTIME,LENGTH,WIDTH,HEIGHT,WEIGHT
0,728502701,DFW4,7,2021-05-20 23:13:09.407,336.0,55.0,229.0,1054.0
1,728497949,DFW4,7,2021-05-20 23:09:01.930,310.0,53.0,293.0,547.0
2,728534397,DFW4,7,2021-05-20 23:43:37.007,236.0,122.0,148.0,636.0
3,728604950,DFW4,7,2021-05-21 00:48:13.167,235.0,131.0,132.0,801.0
4,728422039,DFW4,8,2021-05-20 21:51:27.750,193.0,104.0,129.0,398.0
...,...,...,...,...,...,...,...,...
1155740,727090782,DFW4,7,2021-05-19 18:16:01.143,198.0,30.0,124.0,74.0
1155741,726928611,DFW4,7,2021-05-19 16:10:56.237,293.0,98.0,283.0,573.0
1155742,727115229,DFW4,7,2021-05-19 18:35:27.960,271.0,88.0,158.0,366.0
1155743,727067648,DFW4,7,2021-05-19 17:59:20.513,301.0,60.0,247.0,304.0
1155744,727001778,DFW4,7,2021-05-19 17:17:52.430,368.0,204.0,301.0,611.0

In [5]:
DFW2.to_csv('DFW2.csv')

In [6]:
%%snowflakes DFW3

SELECT
    PARCELKEY, FACILITYNAME, MACHINEID, CREATIONTIME, LENGTH, WIDTH, HEIGHT, WEIGHT
FROM
    "FDR_DWH_DB_PROD"."PARCELAUTOMATION"."PARCEL"
WHERE
    CREATIONTIME >= '2021-06-01' AND CREATIONTIME < '2021-06-15' AND FACILITYNAME = 'DFW4' AND LENGTH != 0 AND WEIGHT != 0;

,PARCELKEY,FACILITYNAME,MACHINEID,CREATIONTIME,LENGTH,WIDTH,HEIGHT,WEIGHT
0,738018826,DFW4,7,2021-06-02 04:48:48.843,216.0,157.0,159.0,340.0
1,738055429,DFW4,7,2021-06-02 05:46:04.147,359.0,37.0,181.0,297.0
2,738045026,DFW4,7,2021-06-02 05:34:29.700,247.0,132.0,144.0,393.0
3,738026961,DFW4,7,2021-06-02 05:12:08.970,257.0,154.0,191.0,397.0
4,738045090,DFW4,7,2021-06-02 05:34:03.317,223.0,153.0,159.0,882.0
...,...,...,...,...,...,...,...,...
1106101,748461148,DFW4,8,2021-06-14 14:43:41.000,286.0,133.0,284.0,3350.0
1106102,748432048,DFW4,7,2021-06-14 14:15:31.603,349.0,98.0,235.0,446.0
1106103,748486194,DFW4,7,2021-06-14 15:06:27.803,320.0,134.0,247.0,880.0
1106104,748417711,DFW4,7,2021-06-14 14:02:12.570,258.0,38.0,173.0,406.0
1106105,748359413,DFW4,8,2021-06-14 13:09:20.577,198.0,102.0,133.0,417.0

In [7]:
DFW3.to_csv('DFW3.csv')

In [8]:
%%snowflakes DFW4

SELECT
    PARCELKEY, FACILITYNAME, MACHINEID, CREATIONTIME, LENGTH, WIDTH, HEIGHT, WEIGHT
FROM
    "FDR_DWH_DB_PROD"."PARCELAUTOMATION"."PARCEL"
WHERE
    CREATIONTIME >= '2021-06-15' AND CREATIONTIME < '2021-07-01' AND FACILITYNAME = 'DFW4' AND LENGTH != 0 AND WEIGHT != 0;

,PARCELKEY,FACILITYNAME,MACHINEID,CREATIONTIME,LENGTH,WIDTH,HEIGHT,WEIGHT
0,753315179,DFW4,8,2021-06-18 18:37:47.667,282.0,100.0,210.0,707.00
1,753279801,DFW4,8,2021-06-18 18:10:31.413,462.0,84.0,310.0,320.00
2,753269193,DFW4,7,2021-06-18 18:01:46.533,525.0,101.0,396.0,745.00
3,753148021,DFW4,7,2021-06-18 16:12:04.420,314.0,47.0,150.0,314.00
4,753245961,DFW4,8,2021-06-18 17:43:55.347,248.0,164.0,208.0,530.00
...,...,...,...,...,...,...,...,...
1372692,758822688,DFW4,7,2021-06-25 12:22:51.883,324.0,79.0,262.0,413.00
1372693,758835982,DFW4,7,2021-06-25 12:37:30.523,222.0,63.0,146.0,428.00
1372694,758824203,DFW4,7,2021-06-25 12:23:53.250,441.0,139.0,343.0,444.72
1372695,758840691,DFW4,7,2021-06-25 12:42:08.150,225.0,68.0,142.0,429.00
1372696,758830985,DFW4,7,2021-06-25 12:31:15.587,362.0,83.0,262.0,384.00

In [9]:
DFW4.to_csv('DFW4.csv')

In [2]:
%%snowflakes DFW5

SELECT
    PARCELKEY, FACILITYNAME, MACHINEID, CREATIONTIME, LENGTH, WIDTH, HEIGHT, WEIGHT
FROM
    "FDR_DWH_DB_PROD"."PARCELAUTOMATION"."PARCEL"
WHERE
    CREATIONTIME >= '2021-04-01' AND CREATIONTIME < '2021-04-15' AND FACILITYNAME = 'DFW4' AND LENGTH != 0 AND WEIGHT != 0;

,PARCELKEY,FACILITYNAME,MACHINEID,CREATIONTIME,LENGTH,WIDTH,HEIGHT,WEIGHT
0,693791612,DFW4,7,2021-04-13 17:30:18.183,376.0,153.0,344.0,1058.0
1,693791613,DFW4,8,2021-04-13 17:30:48.557,443.0,114.0,383.0,1246.0
2,693791621,DFW4,7,2021-04-13 17:29:46.560,266.0,82.0,194.0,326.0
3,693791622,DFW4,8,2021-04-13 17:30:49.033,366.0,64.0,308.0,281.0
4,693791648,DFW4,7,2021-04-13 17:30:19.720,518.0,153.0,471.0,2691.0
...,...,...,...,...,...,...,...,...
1001729,693478788,DFW4,7,2021-04-13 13:09:19.570,264.0,53.0,176.0,354.0
1001730,693478789,DFW4,7,2021-04-13 13:09:19.423,346.0,60.0,297.0,611.0
1001731,693478790,DFW4,8,2021-04-13 13:10:53.523,395.0,157.0,306.0,2815.0
1001732,693478803,DFW4,7,2021-04-13 13:09:20.497,258.0,53.0,172.0,123.0
1001733,693478805,DFW4,7,2021-04-13 13:08:48.110,358.0,53.0,247.0,153.0

In [3]:
DFW5.to_csv('DFW5.csv')

In [4]:
%%snowflakes DFW6

SELECT
    PARCELKEY, FACILITYNAME, MACHINEID, CREATIONTIME, LENGTH, WIDTH, HEIGHT, WEIGHT
FROM
    "FDR_DWH_DB_PROD"."PARCELAUTOMATION"."PARCEL"
WHERE
    CREATIONTIME >= '2021-04-15' AND CREATIONTIME < '2021-05-01' AND FACILITYNAME = 'DFW4' AND LENGTH != 0 AND WEIGHT != 0;

,PARCELKEY,FACILITYNAME,MACHINEID,CREATIONTIME,LENGTH,WIDTH,HEIGHT,WEIGHT
0,699484414,DFW4,7,2021-04-20 03:04:25.523,296.0,123.0,222.0,461.188
1,699484425,DFW4,8,2021-04-20 03:04:25.727,116.0,31.0,57.0,69.000
2,699484427,DFW4,7,2021-04-20 03:04:25.907,296.0,124.0,222.0,2301.000
3,699484434,DFW4,8,2021-04-20 03:04:26.247,301.0,158.0,258.0,4151.000
4,699484449,DFW4,7,2021-04-20 03:04:26.753,263.0,62.0,259.0,81.000
...,...,...,...,...,...,...,...,...
1303303,707538473,DFW4,8,2021-04-28 23:35:11.397,339.0,103.0,235.0,245.000
1303304,707635169,DFW4,7,2021-04-29 00:52:10.097,378.0,101.0,332.0,1063.000
1303305,707538746,DFW4,8,2021-04-28 23:36:25.210,354.0,141.0,207.0,999.000
1303306,707479417,DFW4,8,2021-04-28 22:46:05.377,321.0,204.0,246.0,1556.000
1303307,707530968,DFW4,8,2021-04-28 23:29:20.187,319.0,179.0,309.0,1190.000

In [5]:
DFW6.to_csv('DFW6.csv')

In [6]:
import pandas as pd

DFW = pd.read_csv('DFW1.csv')
DFW2 = pd.read_csv('DFW2.csv')
DFW3 = pd.read_csv('DFW3.csv')
DFW4 = pd.read_csv('DFW4.csv')
DFW5 = pd.read_csv('DFW5.csv')
DFW6 = pd.read_csv('DFW6.csv')

DFW = DFW.append(DFW2)
DFW = DFW.append(DFW3)
DFW = DFW.append(DFW4)
DFW = DFW.append(DFW5)
DFW = DFW.append(DFW6)

DFW.to_csv('dfw.csv')

In [3]:
%%snowflakes DFW8

SELECT
    PARCELKEY, FACILITYNAME, MACHINEID, CREATIONTIME, LENGTH, WIDTH, HEIGHT, WEIGHT
FROM
    "FDR_DWH_DB_PROD"."PARCELAUTOMATION"."PARCEL"
WHERE
    CREATIONTIME >= '2021-01-15' AND CREATIONTIME < '2021-02-01' AND FACILITYNAME = 'DFW4' AND LENGTH != 0 AND WEIGHT != 0;

,PARCELKEY,FACILITYNAME,MACHINEID,CREATIONTIME,LENGTH,WIDTH,HEIGHT,WEIGHT
0,626591666,DFW4,8,2021-01-21 19:35:00.897,251.0,143.0,179.0,1039.0
1,626591670,DFW4,7,2021-01-21 19:35:01.180,313.0,67.0,288.0,784.0
2,626591682,DFW4,7,2021-01-21 19:35:33.710,190.0,33.0,80.0,155.0
3,626591695,DFW4,8,2021-01-21 19:37:06.557,482.0,161.0,350.0,2252.0
4,626591696,DFW4,7,2021-01-21 19:35:34.167,457.0,212.0,359.0,2127.0
...,...,...,...,...,...,...,...,...
981168,631003801,DFW4,7,2021-01-27 16:28:48.120,214.0,33.0,151.0,92.0
981169,631003802,DFW4,8,2021-01-27 16:28:48.313,193.0,102.0,123.0,298.0
981170,631003808,DFW4,7,2021-01-27 16:28:48.580,213.0,46.0,140.0,162.0
981171,631003809,DFW4,8,2021-01-27 16:28:48.763,196.0,102.0,120.0,310.0
981172,631003812,DFW4,7,2021-01-27 16:28:16.847,224.0,127.0,161.0,1401.0

In [4]:
DFW8.to_csv('DFW8.csv')

In [5]:
%%snowflakes DFW9

SELECT
    PARCELKEY, FACILITYNAME, MACHINEID, CREATIONTIME, LENGTH, WIDTH, HEIGHT, WEIGHT
FROM
    "FDR_DWH_DB_PROD"."PARCELAUTOMATION"."PARCEL"
WHERE
    CREATIONTIME >= '2021-02-01' AND CREATIONTIME < '2021-02-15' AND FACILITYNAME = 'DFW4' AND LENGTH != 0 AND WEIGHT != 0;

,PARCELKEY,FACILITYNAME,MACHINEID,CREATIONTIME,LENGTH,WIDTH,HEIGHT,WEIGHT
0,642786338,DFW4,7,2021-02-10 01:11:55.320,166.0,154.0,159.0,647.0
1,642786339,DFW4,7,2021-02-10 01:11:55.330,233.0,120.0,147.0,702.0
2,642786344,DFW4,8,2021-02-10 01:11:23.603,327.0,62.0,293.0,868.0
3,642786354,DFW4,7,2021-02-10 01:11:56.037,313.0,134.0,247.0,803.0
4,642786355,DFW4,8,2021-02-10 01:11:56.220,305.0,71.0,245.0,425.0
...,...,...,...,...,...,...,...,...
1181084,634890343,DFW4,7,2021-02-01 17:46:09.100,159.0,45.0,112.0,456.0
1181085,634890345,DFW4,7,2021-02-01 17:46:41.857,459.0,147.0,456.0,2261.0
1181086,634890366,DFW4,7,2021-02-01 17:46:10.057,242.0,44.0,142.0,256.0
1181087,634890368,DFW4,7,2021-02-01 17:46:42.613,397.0,100.0,365.0,1528.0
1181088,634890377,DFW4,8,2021-02-01 17:46:42.803,272.0,193.0,212.0,1428.0

In [6]:
DFW9.to_csv('DFW9.csv')

In [2]:
%%snowflakes DFW10

SELECT
    PARCELKEY, FACILITYNAME, MACHINEID, CREATIONTIME, LENGTH, WIDTH, HEIGHT, WEIGHT
FROM
    "FDR_DWH_DB_PROD"."PARCELAUTOMATION"."PARCEL"
WHERE
    CREATIONTIME >= '2021-02-15' AND CREATIONTIME < '2021-03-01' AND FACILITYNAME = 'DFW4' AND LENGTH != 0 AND WEIGHT != 0;

,PARCELKEY,FACILITYNAME,MACHINEID,CREATIONTIME,LENGTH,WIDTH,HEIGHT,WEIGHT
0,650101426,DFW4,7,2021-02-19 01:37:34.270,325.0,88.0,278.0,887.0
1,650101430,DFW4,7,2021-02-19 01:38:04.980,303.0,123.0,217.0,1694.0
2,650101438,DFW4,8,2021-02-19 01:37:02.757,191.0,101.0,130.0,407.0
3,650101439,DFW4,7,2021-02-19 01:37:35.203,440.0,103.0,314.0,1090.0
4,650101448,DFW4,7,2021-02-19 01:37:36.270,300.0,122.0,222.0,1041.0
...,...,...,...,...,...,...,...,...
773169,650264647,DFW4,7,2021-02-19 13:17:25.310,435.0,132.0,310.0,453.0
773170,650264788,DFW4,7,2021-02-19 13:17:32.903,382.0,191.0,338.0,1562.0
773171,650264823,DFW4,7,2021-02-19 13:18:16.730,282.0,205.0,237.0,886.0
773172,650264976,DFW4,7,2021-02-19 13:17:44.530,273.0,41.0,234.0,54.0
773173,650265118,DFW4,7,2021-02-19 13:17:52.643,184.0,82.0,128.0,116.0

In [3]:
DFW10.to_csv('DFW10.csv')

In [4]:
%%snowflakes DFW11

SELECT
    PARCELKEY, FACILITYNAME, MACHINEID, CREATIONTIME, LENGTH, WIDTH, HEIGHT, WEIGHT
FROM
    "FDR_DWH_DB_PROD"."PARCELAUTOMATION"."PARCEL"
WHERE
    CREATIONTIME >= '2021-03-01' AND CREATIONTIME < '2021-03-15' AND FACILITYNAME = 'DFW4' AND LENGTH != 0 AND WEIGHT != 0;

,PARCELKEY,FACILITYNAME,MACHINEID,CREATIONTIME,LENGTH,WIDTH,HEIGHT,WEIGHT
0,658556289,DFW4,7,2021-03-02 03:08:30.910,214.0,29.0,124.0,178.0
1,658556300,DFW4,7,2021-03-02 03:09:02.810,217.0,154.0,159.0,403.0
2,658556310,DFW4,7,2021-03-02 03:08:32.750,237.0,29.0,156.0,155.0
3,658556315,DFW4,7,2021-03-02 03:08:34.173,254.0,26.0,128.0,301.0
4,658556319,DFW4,7,2021-03-02 03:09:04.300,260.0,35.0,163.0,239.0
...,...,...,...,...,...,...,...,...
967457,665008562,DFW4,7,2021-03-10 00:18:18.613,272.0,39.0,175.0,346.0
967458,665008580,DFW4,7,2021-03-10 00:18:19.427,251.0,154.0,192.0,601.0
967459,665008581,DFW4,7,2021-03-10 00:18:19.610,215.0,47.0,174.0,130.0
967460,665008592,DFW4,7,2021-03-10 00:18:19.770,316.0,35.0,270.0,83.0
967461,665008598,DFW4,7,2021-03-10 00:18:20.517,358.0,46.0,267.0,296.0

In [5]:
DFW11.to_csv('DFW11.csv')

In [6]:
%%snowflakes DFW12

SELECT
    PARCELKEY, FACILITYNAME, MACHINEID, CREATIONTIME, LENGTH, WIDTH, HEIGHT, WEIGHT
FROM
    "FDR_DWH_DB_PROD"."PARCELAUTOMATION"."PARCEL"
WHERE
    CREATIONTIME >= '2021-03-15' AND CREATIONTIME < '2021-04-01' AND FACILITYNAME = 'DFW4' AND LENGTH != 0 AND WEIGHT != 0;

,PARCELKEY,FACILITYNAME,MACHINEID,CREATIONTIME,LENGTH,WIDTH,HEIGHT,WEIGHT
0,677745877,DFW4,8,2021-03-24 23:13:39.053,304.0,94.0,300.0,488.0
1,677745883,DFW4,7,2021-03-24 23:14:11.163,306.0,70.0,241.0,216.0
2,677745892,DFW4,7,2021-03-24 23:13:39.887,305.0,162.0,265.0,3787.0
3,677745907,DFW4,8,2021-03-24 23:14:42.373,461.0,121.0,318.0,1612.0
4,677745908,DFW4,7,2021-03-24 23:14:12.510,305.0,83.0,260.0,197.0
...,...,...,...,...,...,...,...,...
1367124,679719885,DFW4,7,2021-03-26 19:31:40.890,127.0,27.0,125.0,82.0
1367125,679719892,DFW4,7,2021-03-26 19:31:41.760,293.0,107.0,165.0,348.0
1367126,679719897,DFW4,8,2021-03-26 19:32:12.187,493.0,192.0,402.0,2338.0
1367127,679719898,DFW4,7,2021-03-26 19:31:42.240,288.0,109.0,215.0,361.0
1367128,679719906,DFW4,7,2021-03-26 19:31:10.673,106.0,25.0,94.0,89.0

In [7]:
DFW12.to_csv('DFW12.csv')

In [1]:
import pandas as pd

DFW = pd.read_csv('dfw.csv')
DFW3 = pd.read_csv('DFW8.csv')
DFW4 = pd.read_csv('DFW9.csv')
DFW5 = pd.read_csv('DFW10.csv')
DFW6 = pd.read_csv('DFW11.csv')
DFW7 = pd.read_csv('DFW12.csv')

DFW = DFW.append(DFW3)
DFW = DFW.append(DFW4)
DFW = DFW.append(DFW5)
DFW = DFW.append(DFW6)
DFW = DFW.append(DFW7)

DFW.to_csv('dfw.csv')

In [2]:
%%snowflakes vs

SELECT 
    P.FACILITYNAME, P.CREATIONTIME, P.MACHINEID, P.LENGTH, P.WIDTH, P.HEIGHT, P.WEIGHT, 
    B.BARCODE, PF.MERCHANT, PF.MERCHANT_ORG_KEY 
FROM 
    FDR_DB.FDR_AUTOMATION.PARCEL P
INNER JOIN 
    FDR_DB.FDR_AUTOMATION.BARCODE B
ON 
    B.PARCELKEY = P.PARCELKEY 
INNER JOIN 
    FDR_DB.FDR_EWS.PARCEL_FACILITY PF
ON 
    P.FACILITYNAME = PF.FACILITY_NAME 
AND
    B.BARCODE = PF.PRIMARY_BARCODE
WHERE
    PF.MERCHANT = 'Victoria Secret'
AND
    P.FACILITYNAME = 'DFW4';

,FACILITYNAME,CREATIONTIME,MACHINEID,LENGTH,WIDTH,HEIGHT,WEIGHT,BARCODE,MERCHANT,MERCHANT_ORG_KEY
0,DFW4,2020-08-26 12:31:42.273,7,266.0,78.0,260.0,244.0,420748659274892700465584830458,Victoria Secret,914
1,DFW4,2020-08-26 12:32:15.527,7,339.0,117.0,295.0,431.0,420786609274892700465584811532,Victoria Secret,914
2,DFW4,2020-08-26 12:32:14.100,7,224.0,82.0,177.0,106.0,420770189274892700465584714598,Victoria Secret,914
3,DFW4,2020-08-26 12:33:40.293,7,344.0,100.0,211.0,289.0,420750289274892700465584514662,Victoria Secret,914
4,DFW4,2020-08-26 12:34:24.913,7,251.0,65.0,198.0,182.0,420774799274892700465584674083,Victoria Secret,914
...,...,...,...,...,...,...,...,...,...,...
1268876,DFW4,2020-10-10 01:02:28.707,7,329.0,102.0,262.0,485.0,420720229261292700465601230418,Victoria Secret,914
1268877,DFW4,2020-12-30 15:53:53.497,8,238.0,89.0,188.0,202.0,420774189274892700465621135133,Victoria Secret,914
1268878,DFW4,2020-12-30 16:02:52.193,7,306.0,92.0,282.0,892.0,420730349261292700465621089621,Victoria Secret,914
1268879,DFW4,2020-12-30 15:27:43.647,8,214.0,54.0,194.0,123.0,420770829274892700465621148546,Victoria Secret,914
1268880,DFW4,2020-12-30 15:49:45.647,8,221.0,47.0,194.0,61.0,420720199274892700465621160685,Victoria Secret,914

In [3]:
vs.to_csv('dfw_vs.csv')